# Generated by Django 3.0.7 on 2020-06-14 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='Result',
        ),
    ]
